FROM python:3.7-slim-buster

COPY app /app
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

RUN apt-get update
RUN apt-get install libgomp1

CMD ["python", "/app/main.py"]