FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

COPY app /app
COPY requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

RUN apt-get update
RUN apt-get install libgomp1

