version: '2'
services:
 consul:
   image: "consul"
   hostname: "consul"
   command: "agent -server -ui -node=server-1 -data-dir=/consul/data -bootstrap -client=0.0.0.0"
   ports:
     - "8500:8500"
   volumes:
     - ./consul:/consul/data
 jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker